version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chow-backend
    ports:
      - "8000:8000"
    networks:
      - chow-network

  frontend:
    build: ./frontend
    container_name: chow-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chow-network

networks:
  chow-network:
    driver: bridge